migrate((app) => {
  try {
    app.findCollectionByNameOrId("notifications")
    return
  } catch (_) {}

  const collection = {
    id: "pbc_3053004000",
    listRule: "user = @request.auth.id",
    viewRule: "user = @request.auth.id",
    createRule: "@request.auth.id != ''",
    updateRule: "user = @request.auth.id",
    deleteRule: "user = @request.auth.id",
    name: "notifications",
    type: "base",
    fields: [
      {
        autogeneratePattern: "[a-z0-9]{15}",
        hidden: false,
        id: "text3208210256",
        max: 15,
        min: 15,
        name: "id",
        pattern: "^[a-z0-9]+$",
        presentable: false,
        primaryKey: true,
        required: true,
        system: true,
        type: "text",
      },
      {
        cascadeDelete: false,
        collectionId: "_pb_users_auth_",
        hidden: false,
        id: "relation3053004001",
        maxSelect: 1,
        minSelect: 0,
        name: "user",
        presentable: false,
        required: true,
        system: false,
        type: "relation",
      },
      {
        hidden: false,
        id: "select3053004002",
        maxSelect: 1,
        name: "type",
        presentable: false,
        required: true,
        system: false,
        type: "select",
        values: [
          "friend_request",
          "friend_accept",
          "raid_invite",
          "mission_completed",
        ],
      },
      {
        hidden: false,
        id: "text3053004003",
        max: 120,
        min: 0,
        name: "title",
        pattern: "",
        presentable: false,
        required: true,
        system: false,
        type: "text",
      },
      {
        hidden: false,
        id: "text3053004004",
        max: 300,
        min: 0,
        name: "message",
        pattern: "",
        presentable: false,
        required: false,
        system: false,
        type: "text",
      },
      {
        hidden: false,
        id: "json3053004005",
        maxSize: 2000000,
        name: "data",
        presentable: false,
        required: false,
        system: false,
        type: "json",
      },
      {
        hidden: false,
        id: "text3053004006",
        max: 80,
        min: 0,
        name: "source_type",
        pattern: "",
        presentable: false,
        required: false,
        system: false,
        type: "text",
      },
      {
        hidden: false,
        id: "text3053004007",
        max: 80,
        min: 0,
        name: "source_id",
        pattern: "",
        presentable: false,
        required: false,
        system: false,
        type: "text",
      },
      {
        hidden: false,
        id: "bool3053004008",
        name: "is_read",
        presentable: false,
        required: false,
        system: false,
        type: "bool",
      },
      {
        hidden: false,
        id: "date3053004009",
        max: "",
        min: "",
        name: "read_at",
        presentable: false,
        required: false,
        system: false,
        type: "date",
      },
      {
        hidden: false,
        id: "autodate3053004010",
        name: "created",
        onCreate: true,
        onUpdate: false,
        presentable: false,
        system: false,
        type: "autodate",
      },
      {
        hidden: false,
        id: "autodate3053004011",
        name: "updated",
        onCreate: true,
        onUpdate: true,
        presentable: false,
        system: false,
        type: "autodate",
      },
    ],
    indexes: [
      "CREATE INDEX idx_notifications_user_read_created ON notifications (user, is_read, created)",
      "CREATE INDEX idx_notifications_source ON notifications (source_type, source_id)",
    ],
    system: false,
  }

  app.importCollections([collection], false)
}, (app) => {
  try {
    const collection = app.findCollectionByNameOrId("notifications")
    app.delete(collection)
  } catch (_) {}
})
